import { Category } from '@/types';

export const SEED_CATEGORIES: Category[] = [
  // --- TOP-LEVEL (DEPTH 0) ---
  {
    id: 'cat-skincare',
    name: 'Skincare & Cosmetics',
    slug: 'skincare',
    description: 'Clean organic formulas, high-demand serums, and premium barrier restoration cosmetics.',
    icon: 'Sparkle',
    bannerUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1600&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1608248597359-bb4f53ca0c59?auto=format&fit=crop&w=400&q=80',
    featured: true,
    sortOrder: 10,
    status: 'active',
    parentId: null,
    depth: 0,
    childIds: ['cat-skincare-serums', 'cat-skincare-creams'],
    metaTitle: 'Wholesale Skincare & Cosmetics Catalog | DreamToAchievers',
    metaDescription: 'High-margin wholesale skincare serums, luminosity creams, and organic cosmetic inventory.',
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
  },
  {
    id: 'cat-tech',
    name: 'Tech & Electronics',
    slug: 'tech-electronics',
    description: 'Consumer audio, Bluetooth devices, and smart sports fitness accessories with verified margins.',
    icon: 'Cpu',
    bannerUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=1600&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=400&q=80',
    featured: true,
    sortOrder: 20,
    status: 'active',
    parentId: null,
    depth: 0,
    childIds: ['cat-tech-audio', 'cat-tech-wearables'],
    metaTitle: 'Wholesale Tech & Smart Gadgets | DreamToAchievers',
    metaDescription: 'Active noise cancelling wireless earbuds, fitness smartwatches, and verified electronic gadgets.',
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
  },
  {
    id: 'cat-lifestyle',
    name: 'Home & Executive Lifestyle',
    slug: 'lifestyle',
    description: 'Curated corporate gifting, luxury matte desk ensembles, and bespoke household accessories.',
    icon: 'Package',
    bannerUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1600&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=400&q=80',
    featured: true,
    sortOrder: 30,
    status: 'active',
    parentId: null,
    depth: 0,
    childIds: ['cat-lifestyle-gifting'],
    metaTitle: 'Executive Gifting & Lifestyle Catalog | DreamToAchievers',
    metaDescription: 'High-conversion corporate gift boxes and executive presentation merchandise.',
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
  },
  {
    id: 'cat-wellness',
    name: 'Health & Wellness',
    slug: 'health-wellness',
    description: 'Nutritional wellness, essential oils, and daily vitality boosters with repeat purchase appeal.',
    icon: 'Heart',
    bannerUrl: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&w=1600&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&w=400&q=80',
    featured: false,
    sortOrder: 40,
    status: 'active',
    parentId: null,
    depth: 0,
    childIds: [],
    metaTitle: 'Health & Daily Wellness Essentials | DreamToAchievers',
    metaDescription: 'Nutritional wellness supplements and organic vitality essentials.',
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
  },

  // --- SUB-CATEGORIES (DEPTH 1) ---
  {
    id: 'cat-skincare-serums',
    name: 'Facial Serums & Elixirs',
    slug: 'serums',
    description: 'Concentrated revitalizing serums, hyaluronic moisture bases, and peptide treatments.',
    icon: 'Sparkle',
    featured: true,
    sortOrder: 10,
    status: 'active',
    parentId: 'cat-skincare',
    depth: 1,
    childIds: [],
    metaTitle: 'Wholesale Facial Serums & Repair Elixirs',
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
  },
  {
    id: 'cat-skincare-creams',
    name: 'Luminosity & Day Creams',
    slug: 'creams',
    description: 'Antioxidant daytime moisturizers and vitamin-infused hydrating creams.',
    icon: 'Sparkle',
    featured: false,
    sortOrder: 20,
    status: 'active',
    parentId: 'cat-skincare',
    depth: 1,
    childIds: [],
    metaTitle: 'Wholesale Brightening Creams & Moisturizers',
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
  },
  {
    id: 'cat-tech-audio',
    name: 'Wireless Earbuds & Audio',
    slug: 'audio-earbuds',
    description: 'Active noise cancellation earbuds and titanium acoustic wireless sound systems.',
    icon: 'SpeakerHigh',
    featured: true,
    sortOrder: 10,
    status: 'active',
    parentId: 'cat-tech',
    depth: 1,
    childIds: [],
    metaTitle: 'Wholesale ANC Earbuds & Wireless Audio',
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
  },
  {
    id: 'cat-tech-wearables',
    name: 'Smartwatches & Fitness Trackers',
    slug: 'smartwatches',
    description: 'AMOLED health tracking smartwatches, biometric monitoring, and sports wearables.',
    icon: 'Watch',
    featured: false,
    sortOrder: 20,
    status: 'active',
    parentId: 'cat-tech',
    depth: 1,
    childIds: [],
    metaTitle: 'Wholesale Smartwatches & Wearable Trackers',
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
  },
  {
    id: 'cat-lifestyle-gifting',
    name: 'Executive Gift Sets',
    slug: 'executive-gifts',
    description: 'Luxury corporate gift ensembles, custom metallic pen sets, and presentation boxes.',
    icon: 'Gift',
    featured: true,
    sortOrder: 10,
    status: 'active',
    parentId: 'cat-lifestyle',
    depth: 1,
    childIds: [],
    metaTitle: 'Wholesale Executive Corporate Gift Sets',
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
  },
];
