import { Product } from '@/types';

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-dta-5328',
    name: 'Libas-e-Yousaf',
    slug: 'libas-e-yousaf',
    shortDescription: 'Premium executive festive wear & gift set with luxury packaging.',
    description:
      'Authentic Libas-e-Yousaf executive collection fabricated from high-grade woven textiles with signature presentation chest. Top-selling lifestyle and corporate gifting parcel.',
    category: 'Executive Gift Sets',
    categoryId: 'cat-lifestyle-gifting',
    categoryIds: ['cat-lifestyle', 'cat-lifestyle-gifting'],
    retailPrice: 4500,
    partnerPrice: 2999,
    suggestedSellingPrice: 4500,
    grossMargin: 1501,
    currency: 'PKR',
    imageUrl:
      'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80',
    sku: 'DTA-5328',
    inStock: true,
    isFeatured: true,
    status: 'active',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'prod-dta-6004',
    name: 'Max 1150',
    slug: 'max-1150',
    shortDescription: 'Ultra HD fitness smartwatch with Bluetooth calling and biometric tracking.',
    description:
      'Engineered with high-resolution responsive display, sports modes, IP68 water resistance, dynamic heart-rate and blood oxygen monitoring with wireless rapid magnetic charger.',
    category: 'Smartwatches & Fitness Trackers',
    categoryId: 'cat-tech-wearables',
    categoryIds: ['cat-tech', 'cat-tech-wearables'],
    retailPrice: 3800,
    partnerPrice: 3200,
    suggestedSellingPrice: 3800,
    grossMargin: 600,
    currency: 'PKR',
    imageUrl:
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    sku: 'DTA-6004',
    inStock: true,
    isFeatured: true,
    status: 'active',
    createdAt: '2026-01-02T00:00:00Z',
  },
  {
    id: 'prod-dta-7315',
    name: 'Crown C500',
    slug: 'crown-c500',
    shortDescription: 'Executive crown series smartwatch with high-fidelity speaker & dual straps.',
    description:
      'Premium bezel finish with multi-day battery life, activity and sleep monitoring, custom watch faces, and instant message notifications.',
    category: 'Smartwatches & Fitness Trackers',
    categoryId: 'cat-tech-wearables',
    categoryIds: ['cat-tech', 'cat-tech-wearables'],
    retailPrice: 3800,
    partnerPrice: 3200,
    suggestedSellingPrice: 3800,
    grossMargin: 600,
    currency: 'PKR',
    imageUrl:
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80',
    sku: 'DTA-7315',
    inStock: true,
    isFeatured: true,
    status: 'active',
    createdAt: '2026-01-03T00:00:00Z',
  },
  {
    id: 'prod-dta-3948',
    name: 'Luxury Watch',
    slug: 'luxury-watch',
    shortDescription: 'Sleek luxury timepiece smartwatch with metallic alloy strap and AMOLED display.',
    description:
      'Distinguished styling suitable for executive attire. Delivers precise timekeeping, health telemetry, notifications, and all-day battery efficiency.',
    category: 'Smartwatches & Fitness Trackers',
    categoryId: 'cat-tech-wearables',
    categoryIds: ['cat-tech', 'cat-tech-wearables'],
    retailPrice: 3500,
    partnerPrice: 2800,
    suggestedSellingPrice: 3500,
    grossMargin: 700,
    currency: 'PKR',
    imageUrl:
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80',
    sku: 'DTA-3948',
    inStock: true,
    isFeatured: true,
    status: 'active',
    createdAt: '2026-01-04T00:00:00Z',
  },
];
