import { Product } from '@/types';

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    name: 'Luxe Botanical Skin Repair Elixir',
    slug: 'luxe-botanical-skin-repair-elixir',
    shortDescription: 'Advanced organic revitalizing serum formulated with rare botanical extracts.',
    description:
      'Engineered for maximum skin barrier restoration, this premium facial elixir features cold-pressed botanical squalane, multi-molecular hyaluronic acid, and organic rosehip essence. High-demand consumer product with strong repeat purchase frequency.',
    category: 'Skincare & Cosmetics',
    categoryId: 'cat-skincare-serums',
    categoryIds: ['cat-skincare', 'cat-skincare-serums'],
    retailPrice: 2500,
    partnerPrice: 2000,
    suggestedSellingPrice: 2500,
    grossMargin: 500,
    currency: 'PKR',
    imageUrl: 'https://images.unsplash.com/photo-1608248597359-bb4f53ca0c59?auto=format&fit=crop&w=800&q=80',
    sku: 'DTA-SKN-001',
    inStock: true,
    isFeatured: true,
    status: 'active',
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'prod-002',
    name: 'Aura Glow Vitamin C Luminosity Cream',
    slug: 'aura-glow-vitamin-c-luminosity-cream',
    shortDescription: 'Brightening daily antioxidant moisturizer for radiant, hydrated skin.',
    description:
      'Formulated with 12% stabilized ethyl ascorbic acid and niacinamide to enhance skin radiance and even out tone. Comes in luxury airless cosmetic packaging with proven viral social appeal.',
    category: 'Skincare & Cosmetics',
    categoryId: 'cat-skincare-creams',
    categoryIds: ['cat-skincare', 'cat-skincare-creams'],
    retailPrice: 2800,
    partnerPrice: 2200,
    suggestedSellingPrice: 2800,
    grossMargin: 600,
    currency: 'PKR',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
    sku: 'DTA-SKN-002',
    inStock: true,
    isFeatured: true,
    status: 'active',
    createdAt: '2026-01-20T00:00:00Z',
  },
  {
    id: 'prod-003',
    name: 'Quantum Sound ANC Wireless Earbuds',
    slug: 'quantum-sound-anc-wireless-earbuds',
    shortDescription: 'Active noise-canceling stereo earbuds with 36-hour playback battery life.',
    description:
      'High-fidelity titanium dynamic audio drivers, Bluetooth 5.4 multi-point connectivity, and crystal-clear ENC microphone system. Compact pocket charging capsule with sleek metallic finish.',
    category: 'Tech & Electronics',
    categoryId: 'cat-tech-audio',
    categoryIds: ['cat-tech', 'cat-tech-audio'],
    retailPrice: 4500,
    partnerPrice: 3500,
    suggestedSellingPrice: 4500,
    grossMargin: 1000,
    currency: 'PKR',
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    sku: 'DTA-ELC-001',
    inStock: true,
    isFeatured: true,
    status: 'active',
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'prod-004',
    name: 'Apex Precision Fitness Smartwatch Pro',
    slug: 'apex-precision-fitness-smartwatch-pro',
    shortDescription: 'AMOLED health and sports tracking watch with continuous SpO2 and heart-rate.',
    description:
      'Featuring a brilliant 1.43-inch HD AMOLED screen, IP68 water resistance, GPS workout tracking, and 14-day standby power. Ideal companion for fitness enthusiasts and everyday executives.',
    category: 'Tech & Electronics',
    categoryId: 'cat-tech-wearables',
    categoryIds: ['cat-tech', 'cat-tech-wearables'],
    retailPrice: 6200,
    partnerPrice: 4900,
    suggestedSellingPrice: 6200,
    grossMargin: 1300,
    currency: 'PKR',
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    sku: 'DTA-ELC-002',
    inStock: true,
    isFeatured: false,
    status: 'active',
    createdAt: '2026-02-10T00:00:00Z',
  },
  {
    id: 'prod-005',
    name: 'Signature Executive Matte Gift Box Ensemble',
    slug: 'signature-executive-matte-gift-box-ensemble',
    shortDescription: 'Curated luxury lifestyle collection with metallic pen, wallet, and thermal tumbler.',
    description:
      'Handcrafted premium corporate gift set encased in a custom matte gold-embossed presentation chest. Exceptional conversion rate for corporate orders and special occasion gifting.',
    category: 'Home & Executive Lifestyle',
    categoryId: 'cat-lifestyle-gifting',
    categoryIds: ['cat-lifestyle', 'cat-lifestyle-gifting'],
    retailPrice: 3800,
    partnerPrice: 2900,
    suggestedSellingPrice: 3800,
    grossMargin: 900,
    currency: 'PKR',
    imageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80',
    sku: 'DTA-LIF-001',
    inStock: true,
    isFeatured: true,
    status: 'active',
    createdAt: '2026-02-15T00:00:00Z',
  },
  {
    id: 'prod-006',
    name: 'Pure Hydro Thermal Infusion Flask (750ml)',
    slug: 'pure-hydro-thermal-infusion-flask',
    shortDescription: 'Double-walled stainless steel vacuum flask with digital temperature display.',
    description:
      'Keeps beverages boiling hot for 18 hours or ice cold for 24 hours. Built with food-grade 316 stainless steel interior and a touch-activated LED temperature readout on the cap.',
    category: 'Home & Executive Lifestyle',
    categoryId: 'cat-lifestyle-gifting',
    categoryIds: ['cat-lifestyle', 'cat-lifestyle-gifting'],
    retailPrice: 2400,
    partnerPrice: 1900,
    suggestedSellingPrice: 2400,
    grossMargin: 500,
    currency: 'PKR',
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
    sku: 'DTA-LIF-002',
    inStock: true,
    isFeatured: false,
    status: 'active',
    createdAt: '2026-02-20T00:00:00Z',
  },
];
