import { VideoTutorial } from '@/types';

export const INITIAL_TUTORIALS: VideoTutorial[] = [
  {
    id: 'tut-1',
    title: 'How Dream to Achievers Wholesale & Dropshipping Works',
    description: 'A complete visual masterclass explaining how to choose wholesale products, take retail customer orders, and let our logistics ship via courier COD across Pakistan.',
    rawInput: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    embedUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ?rel=0&modestbranding=1',
    sourceType: 'youtube',
    category: 'Getting Started',
    duration: '4:30',
    thumbnailUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=800&q=80',
    sourceDirectUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    sortOrder: 1,
    isActive: true,
    featured: true,
    createdAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'tut-2',
    title: 'How to Pick High-Profit Wholesale Products & Share on WhatsApp',
    description: 'Learn how to calculate your gross margins (+PKR 500 to 1,500 per unit) and broadcast verified inventory catalogs to your local network and customer lists.',
    rawInput: 'https://www.youtube.com/watch?v=L_LUpnjgPso',
    embedUrl: 'https://www.youtube-nocookie.com/embed/L_LUpnjgPso?rel=0&modestbranding=1',
    sourceType: 'youtube',
    category: 'Product Sourcing',
    duration: '6:15',
    thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    sourceDirectUrl: 'https://www.youtube.com/watch?v=L_LUpnjgPso',
    sortOrder: 2,
    isActive: true,
    featured: false,
    createdAt: '2026-09-02T11:30:00.000Z',
  },
  {
    id: 'tut-3',
    title: 'Nationwide Courier COD Delivery & Withdrawing Profit Margins',
    description: 'Step-by-step tutorial on tracking orders in the partner terminal, courier dispatch timelines, cash collection, and withdrawing to JazzCash, Easypaisa, or Bank.',
    rawInput: 'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
    embedUrl: 'https://www.youtube-nocookie.com/embed/kJQP7kiw5Fk?rel=0&modestbranding=1',
    sourceType: 'youtube',
    category: 'COD & Logistics',
    duration: '5:45',
    thumbnailUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    sourceDirectUrl: 'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
    sortOrder: 3,
    isActive: true,
    featured: false,
    createdAt: '2026-09-03T14:15:00.000Z',
  },
];
